/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab1;

import javax.swing.JOptionPane;

/**
 *
 * @author pvsla
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Caculator
     */
    public Calculator() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public boolean checkNull() {
        if (txtFirstNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "First number error !!!");
            txtFirstNumber.requestFocus();
            return false;
        } else if (txtSecondNumber.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Second number error !!!");
            txtSecondNumber.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSummation = new javax.swing.JButton();
        btnSubtraction = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        txtFirstNumber = new javax.swing.JTextField();
        txtSecondNumber = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First number");

        jLabel2.setText("Second number");

        jLabel3.setText("Result");

        btnSummation.setText("+");
        btnSummation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSummationActionPerformed(evt);
            }
        });

        btnSubtraction.setText("-");
        btnSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtractionActionPerformed(evt);
            }
        });

        btnMultiplication.setText("*");
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });

        btnDivision.setText("/");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSummation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubtraction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultiplication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDivision))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFirstNumber)
                            .addComponent(txtSecondNumber)
                            .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSecondNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSummation)
                    .addComponent(btnSubtraction)
                    .addComponent(btnMultiplication)
                    .addComponent(btnDivision))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSummationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSummationActionPerformed
        // TODO add your handling code here:
//        float so1, so2;
//        double ketqua;
//        if (checkNull()) {
//            so1 = Float.parseFloat(txtFirstNumber.getText());
//            so2 = Float.parseFloat(txtSecondNumber.getText());
//            ketqua = so1 + so2;
//            txtResult.setText(ketqua + "");
//        }
        StringBuilder sb = new StringBuilder();
        String num1 = txtFirstNumber.getText();
        if (num1.equals("")) {
            sb.append("First number error !!!\n");
        }
        String num2 = txtSecondNumber.getText();
        if (num2.equals("")) {
            sb.append("Second number error !!!\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
        }
        try {
            float n1 = Float.parseFloat(num1);
            float n2 = Float.parseFloat(num2);
            txtResult.setText("" + (n1 + n2));
        } catch (Exception e) {
            e.printStackTrace();//nhan biet loi
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSummationActionPerformed

    private void btnSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtractionActionPerformed
        // TODO add your handling code here:
//        float so1, so2;
//        double ketqua;
//        if (checkNull()) {
//            so1 = Float.parseFloat(txtFirstNumber.getText());
//            so2 = Float.parseFloat(txtSecondNumber.getText());
//            ketqua = so1 - so2;
//            txtResult.setText(ketqua + "");
//        }
        StringBuilder sb = new StringBuilder();
        String num1 = txtFirstNumber.getText();
        if (num1.equals("")) {
            sb.append("First number error !!!\n");
        }
        String num2 = txtSecondNumber.getText();
        if (num2.equals("")) {
            sb.append("Second number error !!!\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
        }
        try {
            float n1 = Float.parseFloat(num1);
            float n2 = Float.parseFloat(num2);
            txtResult.setText("" + (n1 - n2));
        } catch (Exception e) {
            e.printStackTrace();//nhan biet loi
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSubtractionActionPerformed

    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
        // TODO add your handling code here:
//        float so1, so2;
//        double ketqua;
//        if (checkNull()) {
//            so1 = Float.parseFloat(txtFirstNumber.getText());
//            so2 = Float.parseFloat(txtSecondNumber.getText());
//            ketqua = so1 * so2;
//            txtResult.setText(ketqua + "");
//        }
        StringBuilder sb = new StringBuilder();
        String num1 = txtFirstNumber.getText();
        if (num1.equals("")) {
            sb.append("First number error !!!\n");
        }
        String num2 = txtSecondNumber.getText();
        if (num2.equals("")) {
            sb.append("Second number error !!!\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb.toString());
        }
        try {
            float n1 = Float.parseFloat(num1);
            float n2 = Float.parseFloat(num2);
            txtResult.setText("" + (n1 * n2));
        } catch (Exception e) {
            e.printStackTrace();//nhan biet loi
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        // TODO add your handling code here:
        float so1, so2;
        double ketqua;
        if (checkNull()) {
            so1 = Float.parseFloat(txtFirstNumber.getText());
            so2 = Float.parseFloat(txtSecondNumber.getText());
            ketqua = so1 / so2;
            txtResult.setText(ketqua + "");
        }
//        StringBuilder sb = new StringBuilder();
//        String num1 = txtFirstNumber.getText();
//        if (num1.equals("")) {
//            sb.append("First number error !!!\n");
//        }
//        String num2 = txtSecondNumber.getText();
//        if (num2.equals("")) {
//            sb.append("Second number error !!!\n");
//        }
//        if (sb.length() > 0) {
//            JOptionPane.showMessageDialog(this, sb.toString());
//        }
//        try {
//            float n1 = Float.parseFloat(num1);
//            float n2 = Float.parseFloat(num2);
//            txtResult.setText("" + (n1 / n2));
//        } catch (Exception e) {
//            e.printStackTrace();//nhan biet loi
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnSubtraction;
    private javax.swing.JButton btnSummation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFirstNumber;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtSecondNumber;
    // End of variables declaration//GEN-END:variables
}
